apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: harika402/frontend:v1
        envFrom:
        - configMapRef:
            name: frontend



---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-port 
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
        
